parameters:
  buildConfiguration: 'Release'
  environment: 'dev'
  appName: 'dev'

jobs:
- deployment: Deploy
  pool:
    vmImage: 'ubuntu-18.04'
  environment: ${{ parameters.environment }}
  variables:
  - group: Release
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: drop
        - task: AzureWebApp@1
          displayName: 'Azure App Service Deploy: website'
          inputs:
            azureSubscription: 'Resource Manager - Tailspin - Space Game'
            appName: '${{ parameters.appName }}'
            package: '$(Pipeline.Workspace)/drop/${{ parameters.buildConfiguration }}/*.zip'
